#!/bin/sh
echo 'mount -t aufs -o dirs=/$1:/$2 aufs $2' > /bin/mountsfsrw
chmod +x /bin/mountsfsrw

install -d /etc/modprobe.d

#FIXME :: it works ???
echo "blacklist pcspkr" > /etc/modprobe.d/pcspkr.conf
echo "blacklist snd_pcsp" > /etc/modprobe.d/snd_pcsp.conf
echo "blacklist evbug" > /etc/modprobe.d/blacklist.conf

INTEL=""
NVIDIA=""
lspci | grep VGA | grep -i Intel >/dev/null && INTEL=OK
lspci | grep VGA | grep -i NVIDIA >/dev/null && NVIDIA=OK
if [ -n "$INTEL" ] && [ -n "$NVIDIA" ] 
then
OPTIMUS=INTEL
grep optimus=nouveau /proc/cmdline && OPTIMUS=NOUVEAU
if [ "$OPTIMUS" = "INTEL" ]
then
echo "Optimus detected, use optimus=nouveau to enable Nvidia card" > /dev/tty1 
echo blacklist nouveau >> /etc/modprobe.d/blacklist.conf
else
echo "Optimus detected, delete optimus=nouveau to enable Intel card" > /dev/tty1 
echo blacklist i915 >> /etc/modprobe.d/blacklist.conf
fi
fi

echo -n "Loading kernel modules "
echo -n "."
udevadm trigger --action=add --type=subsystems
echo -n "."
udevadm trigger --action=add --type=devices
echo -n "."
echo -n " udevadm settle "
udevadm settle
echo -n "."
modprobe psmouse
modprobe evdev
modprobe analog
echo -n "."
echo " Done"

acpid
echo "killall Xorg" > /fix/lubuntu-logout
echo "killall lxdm-binary" >> /fix/lubuntu-logout
chmod +x /fix/lubuntu-logout

/usr/libexec/bluetooth/bluetoothd &

/ydfs/fix/usb-disk-cache

[ -e /dev/kmsg ] && mv /dev/kmsg /dev/kmsg.udev
