#!/bin/sh
  if [ -e login-utils/su.c ]
  then
	echo "Build util-linux"
	srcdir="."
	for file in pam-login pam-common pam-su pam-remote pam-runuser
	do
	  [ ! -e $file ] && wget --no-check-certificate https://gitlab.archlinux.org/archlinux/packaging/packages/util-linux/-/raw/main/$file?ref_type=heads  --output-document=$file
	  [ ! -e $file ] && exit 1
	done
	 # install PAM files for login-utils
echo "Install /etc/pam.d files"
  install -Dm644 "$srcdir/pam-common" "$pkgdir/etc/pam.d/chfn"
  install -m644 "$srcdir/pam-common" "$pkgdir/etc/pam.d/chsh"
  install -m644 "$srcdir/pam-login" "$pkgdir/etc/pam.d/login"
  install -m644 "$srcdir/pam-su" "${pkgdir}/etc/pam.d/su"
  install -m644 "$srcdir/pam-su" "${pkgdir}/etc/pam.d/su-l"
  install -m0644 $srcdir/pam-remote "${pkgdir}/etc/pam.d/remote"
  install -m0644 $srcdir/pam-runuser "${pkgdir}/etc/pam.d/runuser"
  install -m0644 $srcdir/pam-runuser "${pkgdir}/etc/pam.d/runuser-l"

echo "done"
sleep 4
  fi
