#!/bin/bash
install -d $HOME/archpkg
cd $HOME/archpkg
URL=https://gitlab.archlinux.org/archlinux/packaging/packages
PKG=$1
SHORT=${PKG:0:2}
#[ -e $PKG ] && rm $PKG
if [ ! -e $HOME/archpkg/$PKG ]
then
	wget --no-check-certificate -q "$URL""/""$1""/-/raw/main/PKGBUILD" -O $HOME/archpkg/$PKG || wget --no-check-certificate -q "$URL3" -O $HOME/archpkg/$PKG || wget --no-check-certificate "$URL4" -O $HOME/archpkg/$PKG || ERROR=1
fi

. $HOME/archpkg/$PKG

for i in ${!source[*]}
do 
 if [ $i -gt 0 ]
 then
#	echo ${source[i]}
	echo $URL/$pkg//-/raw/main/${source[i]} >> $HOME/.archpatches
 fi
 #break
done
