#!/bin/bash
install -d $HOME/archpkg
cd $HOME/archpkg
URL=https://gitlab.archlinux.org/archlinux/packaging/packages/
PKG=$1
SHORT=${PKG:0:2}

if [ ! -e $HOME/archpkg/$PKG ]
then
wget --no-check-certificate -q "$URL""/""$1""//-/raw/main/PKGBUILD" -O $HOME/archpkg/$PKG || ERROR=1
fi

. $HOME/archpkg/$PKG

for i in ${!source[*]}
do 
	SOURCE=${source[i]}
	echo "DEBUG SOURCE : $SOURCE"
	FILE=${source[i]}
	echo ${source[i]} |grep '::' && SOURCE=https:`echo ${source[i]} | cut -d':' -f8`
	echo "DEBUG SOURCE : $SOURCE"
 if [ $i -gt 0 ]
 then
#	echo ${source[i]}
	PATCHURL=https://gitlab.archlinux.org/archlinux/packaging/packages/$PKG/-/raw/main/$SOURCE?ref_type=heads
	PATCHURL4=$SOURCE
	install -d /tmp/patches
	wget $PATCHURL -O /tmp/patches/$FILE || wget $PATCHURL4 -O /tmp/patches/$FILE 
 fi
 #break
done
