#!/bin/bash
install -d $HOME/archpkg
cd $HOME/archpkg
#https://gitlab.archlinux.org/archlinux/packaging/packages/util-linux/-/raw/main/$file?ref_type=heads
URL=https://gitlab.archlinux.org/archlinux/packaging/packages/
PKG=$1
[ -e $PKG ] && rm $PKG
wget -q "$URL""/""$1""/-/raw/main/$file?ref_type=heads" -O $HOME/archpkg/$PKG || exit 1

source $HOME/archpkg/$PKG

for i in ${!source[*]}
do 
 echo ${source[i]}
 break
done
